export const series = [
  {
    id: "79275307-aa8f-4750-9de6-8ba1617408a0",
    slug: "hijack",
    content_type: "s",
    title: "Hijack",
    overview:
      "A plane from Dubai to London is hijacked over a 7-hour flight, while authorities on the ground scramble for answers.",
    availability_pros:
      "1 episodes (33%) are available to watch free online (Apple TV+). 3 episodes (100%) are available to stream on a subscription service (Apple TV+).",
    imdb_rating: 7.7,
    rt_critics_rating: null,
    rg_content_score: 73.99,
    has_poster: true,
    poster_blur: "v37nm~RP00S500o~VrNG~WR-t7%MNZMyyDxu8_ozxbkC^+bHo}tQ00jt%hMx",
    has_backdrop: true,
    backdrop_blur:
      "q34ol].m9FyX.8iwbHMxxFo#XTadjFtRofROROV@ogs:V@Rjj[tRo|ayVtofozRjV@tRMdfktlaeV?bafkofV@fPogj[ayWBaeoz",
    released_on: "2023-06-28T00:00:00",
    classification: "18+",
    sources: ["apple_tv_plus", "apple_tv_free"],
    genres: [3, 32],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 1,
    featured_services: [],
    episode_source_count: 3,
  },
  {
    id: "d70e8b13-fb3d-4f3a-9ec1-6b6184824c6c",
    slug: "silo-2023",
    content_type: "s",
    title: "Silo",
    overview:
      "Men and women live in a giant silo underground with several regulations which they believe are in place to protect them from the toxic and ruined world on the surface.",
    availability_pros:
      "1 episodes (10%) are available to watch free online (Apple TV+). 10 episodes (100%) are available to stream on a subscription service (Apple TV+).",
    imdb_rating: 8.1,
    rt_critics_rating: null,
    rg_content_score: 79.12,
    has_poster: true,
    poster_blur: "vuK[OoR,wKs-}BazxEa|V_oKn*S3$zj@WWfQNJfjkAo1I@bGR,azxWazjaWp",
    has_backdrop: true,
    backdrop_blur:
      "q_Ln9YoKnjn*W:odWWaz}VWWoKazWpfQoKfjNIWWW:WpazWDsnj@W:s-S3jtjtbGWWazoKjaoKoKoKoKS3fjR,R,oKazoKazbGj@",
    released_on: "2023-05-05T00:00:00",
    classification: "18+",
    sources: ["apple_tv_plus", "apple_tv_free"],
    genres: [13, 3],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: true,
    watchlisted: false,
    seen: false,
    season_count: 2,
    featured_services: [],
    episode_source_count: 10,
  },
  {
    id: "bbe35754-3b9c-4b21-b567-9103083d5d06",
    slug: "yellowstone-2018",
    content_type: "s",
    title: "Yellowstone",
    overview:
      "A ranching family in Montana faces off against others encroaching on their land.",
    availability_pros:
      "1 episodes (2%) are available to watch free online (Paramount Network). 47 episodes (98%) are available to stream on a subscription service (Peacock Premium, Philo, fuboTV, and 2 others). 10 episodes (21%) are available to stream on a popular TV everywhere service (Paramount Network). 47 episodes (98%) are available to rent or buy from $1.99 on 7 services (iTunes, Apple TV, Google Play, and 4 others).",
    imdb_rating: 8.7,
    rt_critics_rating: 82,
    rg_content_score: 89.7,
    has_poster: true,
    poster_blur: "vTD]M8t7x[j@~poextofRPRkWCof9ZR*RjWBR+ofRjNG-pt6NGWBtRofWBof",
    has_backdrop: true,
    backdrop_blur:
      "qGFYcAD*t7D*9FWBWXxt~VofD*kCIVWBtQxu00xtflxtxuRjofWVE2t6oLay%LkCe.IU%MayIVM|xtt7s.fQ-pWVNGayaeofbHxu",
    released_on: "2018-06-19T00:00:00",
    classification: "18+",
    sources: [
      "peacock",
      "philo",
      "fubo_tv",
      "paramount_network_tve",
      "directv",
      "tvision",
      "paramount_network_free",
    ],
    genres: [3, 36],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 5,
    featured_services: [],
    episode_source_count: 0,
  },
  {
    id: "64289e71-cfff-468c-be72-1fe3526c48f8",
    slug: "jury-duty-2023",
    content_type: "s",
    title: "Jury Duty",
    overview:
      "It follows the workings of an American jury trial through the eyes of Ronald Gladden, a juror who is unaware the entire case is fake. Everyone except him is an actor, and everything that happens is carefully planned.",
    availability_pros:
      "8 episodes (100%) are available to watch free online (Freevee and Prime Video). 8 episodes (100%) are available to stream on a popular subscription service (Prime Video).",
    imdb_rating: 8.4,
    rt_critics_rating: null,
    rg_content_score: 78.96,
    has_poster: true,
    poster_blur: "vC86EZVXE+pIysaKR*ozD*oz#kaKK+jY#,V@gMaeenWB$*kCNHj?VYaeXmof",
    has_backdrop: true,
    backdrop_blur:
      "q67MZ^U^9wuP:Pn4E2S4.Ti_NGX8xanNNbXSL2o~$zVYKjbvw]ofJ.Vs%2tRIoS~#ln4Y5V@ivkCS~b^wIr=t7kCWqV@o}ozWBf+",
    released_on: "2023-04-06T00:00:00",
    classification: "16+",
    sources: ["amazon_prime", "imdb_tv", "amazon_prime_free"],
    genres: [9],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 1,
    featured_services: [],
    episode_source_count: 8,
  },
  {
    id: "f581e6d9-734d-4530-8fcb-76f1152b9325",
    slug: "the-lincoln-lawyer-2022",
    content_type: "s",
    title: "The Lincoln Lawyer",
    overview:
      "An iconoclastic idealist runs his law practice out of the back of his Lincoln Town Car in this series based on Michael Connelly's bestselling novels.",
    availability_pros:
      "1 episodes (7%) are available to watch free online (Apple TV+). 15 episodes (100%) are available to stream on a popular subscription service (Netflix, Netflix Basic, and Apple TV+). 8 episodes (53%) are available to rent or buy from $1.99 on 1 service (Apple TV).",
    imdb_rating: 7.7,
    rt_critics_rating: null,
    rg_content_score: 78.97,
    has_poster: true,
    poster_blur: "vTGHVcoeM_f6}[fPIVay0hWBNwbH0zay%2j[M_of%2jZrqj[t7f6aeayR-j[",
    has_backdrop: true,
    backdrop_blur:
      "qiE_25NHNHW;j?s.R+WV}sNbNHf*j@jZj[a|w|S4S4s-jsR*s:a}R-S2WWs.ayWXj?ayR-j@j?soayWXoJjsR+oeoLjZazWVoLj[",
    released_on: "2022-05-13T00:00:00",
    classification: "18+",
    sources: ["netflix", "netflix_basic", "apple_tv_plus", "apple_tv_free"],
    genres: [10, 3],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 2,
    featured_services: [],
    episode_source_count: 15,
  },
  {
    id: "15b26fe5-d9ed-44de-99a8-b2e793a315af",
    slug: "the-crowded-room-2023",
    content_type: "s",
    title: "The Crowded Room",
    overview:
      "In Manhattan in the summer of 1979, a young man is arrested for a shocking crime, and an unlikely investigator must solve the mystery behind it before the true criminal strikes again.",
    availability_pros:
      "1 episodes (14%) are available to watch free online (Apple TV+). 7 episodes (100%) are available to stream on a subscription service (Apple TV+).",
    imdb_rating: 7,
    rt_critics_rating: null,
    rg_content_score: 73.44,
    has_poster: true,
    poster_blur: "vCHcvG0yQRF29avy3r-V0MvhL2WCYPJ6IUt7}r%1[VI:0eFy^PEMKP;gV@xu",
    has_backdrop: true,
    backdrop_blur:
      "qIH0Ch1GvMv#3E=|{cS#7Lv}2un6EgShs8tQ,sazsmJ*W=aywxayI;S#,p$%,?s9JUR*Ef$PX8JTR*a#Nx$gX8WUs:WCe.SOa{kC",
    released_on: "2023-06-09T00:00:00",
    classification: "18+",
    sources: ["apple_tv_plus", "apple_tv_free"],
    genres: [10, 23],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 1,
    featured_services: [],
    episode_source_count: 7,
  },
  {
    id: "f5acc8bd-7966-4121-8341-683297004abe",
    slug: "happy-valley-2014",
    content_type: "s",
    title: "Happy Valley",
    overview:
      "Yorkshire-based crime drama centering on the personal and professional life of Police Sergeant Catherine Cawood.",
    availability_pros:
      "1 episodes (6%) are available to watch free online (Prime Video). 18 episodes (100%) are available to stream on a popular subscription service (Prime Video, Philo, fuboTV, and 3 others). 5 episodes (28%) are available to stream on a TV everywhere service (BBC America). 18 episodes (100%) are available to rent or buy from $1.99 on 6 services (iTunes, Apple TV, Google Play, and 3 others).",
    imdb_rating: 8.5,
    rt_critics_rating: 98,
    rg_content_score: 86.5,
    has_poster: true,
    poster_blur: "vKH2TL0KWFfl9a%3IUj[00-;WAax~WIT-;kCtPogRjogIAR-NGWBtRjExuWB",
    has_backdrop: true,
    backdrop_blur:
      "q5Ctzm000000MKM0yY%z00%Mt,H?VrWDVs.800_MMJ%gWUtRr=M{q[IVm,o~t-nhS$IT9GD%-;$etkpIIAZ%RPnOIUx]%LyDRjM{",
    released_on: "2014-04-29T00:00:00",
    classification: "18+",
    sources: [
      "amazon_prime",
      "philo",
      "fubo_tv",
      "amc_plus",
      "acorntv",
      "bbc_america_tve",
      "amazon_prime_free",
      "directv",
    ],
    genres: [10, 3],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 3,
    featured_services: [],
    episode_source_count: 1,
  },
  {
    id: "656cdc0b-0e31-4507-b75d-ef743ce997dd",
    slug: "star-trek-strange-new-worlds-2022",
    content_type: "s",
    title: "Star Trek: Strange New Worlds",
    overview:
      "A prequel to Star Trek: The Original Series, the show follows the crew of the USS Enterprise under Captain Christopher Pike.",
    availability_pros:
      "11 episodes (46%) are available to watch free online (PlutoTV and Prime Video). 24 episodes (100%) are available to stream on a popular subscription service (Prime Video and Paramount+). 10 episodes (42%) are available to rent or buy from $1.99 on 4 services (Apple TV, Prime Video, Microsoft, and 1 other).",
    imdb_rating: 8.2,
    rt_critics_rating: null,
    rg_content_score: 83.25,
    has_poster: true,
    poster_blur: "vKEx*8xv0jR%~poy9xRi0zaJi^Ri0Li^$LjY4nax-poz-nWYX9ozo#WCt6j]",
    has_backdrop: true,
    backdrop_blur:
      "qSEe+0BC5p,,R%wNVtou~pIpE2$MjYkWV[bqogVrRQoMspkoRlShNLw[oINyofoxerR-jFofRja$ofoeoMWCocf+RQoJkCkCofWC",
    released_on: "2022-05-05T00:00:00",
    classification: "7+",
    sources: ["amazon_prime", "paramount_plus", "plutotv", "amazon_prime_free"],
    genres: [13, 5],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 3,
    featured_services: [],
    episode_source_count: 21,
  },
  {
    id: "40fd9b45-5fee-4c3d-a169-cd8f0710ffa4",
    slug: "the-walking-dead-dead-city-2023",
    content_type: "s",
    title: "The Walking Dead: Dead City",
    overview:
      "Maggie and Negan travel to a post-apocalyptic Manhattan, long ago cut off from the mainland. The crumbling city is filled with the dead and denizens who have made New York City their own world full of anarchy, danger, beauty, and terror.",
    availability_pros:
      "1 episodes (25%) are available to watch free online (The Roku Channel and Prime Video). 4 episodes (100%) are available to stream on a popular subscription service (Prime Video, Philo, AMC+, and 2 others). 3 episodes (75%) are available to stream on a popular TV everywhere service (AMC, IFC, Sundance, and 1 other). 3 episodes (75%) are available to rent or buy from $1.99 on 3 services (Apple TV, Prime Video, and Vudu).",
    imdb_rating: 7.8,
    rt_critics_rating: null,
    rg_content_score: 75.1,
    has_poster: true,
    poster_blur: "vH7_$fkCD%Xn7%W=+aof+aozNta0VDX9k=jYIAenxtg3=si_I=bvAcX8$yjv",
    has_backdrop: true,
    backdrop_blur:
      "qA3,dBNdqZRjb^kWXnofYRoKVDofbwWBo2W=MdxDTJt6WYa1n4W=rCR-tmWBeToLWCt6nNW=o}V@nNbcgNkCNGs.Sin%jYW=ozWX",
    released_on: "2023-06-18T00:00:00",
    classification: "18+",
    sources: [
      "amazon_prime",
      "philo",
      "amc_plus",
      "amc",
      "ifc",
      "shudder",
      "roku_channel",
      "sundance_tveverywhere",
      "bbc_america_tve",
      "amazon_prime_free",
      "directv",
    ],
    genres: [3, 5],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 1,
    featured_services: [],
    episode_source_count: 1,
  },
  {
    id: "c1ca7883-d7f8-4e37-a1d3-b5dc61f9c93c",
    slug: "outlander-2014",
    content_type: "s",
    title: "Outlander",
    overview:
      "Claire Beauchamp Randall, a nurse in World War II, mysteriously goes back in time to Scotland in 1743. There, she meets a dashing Highland warrior and gets drawn into an epic rebellion.",
    availability_pros:
      "1 episodes (1%) are available to watch free online (The Roku Channel, Prime Video, and Starz). 79 episodes (98%) are available to stream on a popular subscription service (Netflix, Netflix Basic, Prime Video, and 2 others). 75 episodes (93%) are available to stream on a popular TV everywhere service (Starz). 75 episodes (93%) are available to rent or buy from $1.99 on 5 services (Apple TV, Google Play, Prime Video, and 2 others).",
    imdb_rating: 8.4,
    rt_critics_rating: 89,
    rg_content_score: 89.64,
    has_poster: true,
    poster_blur: "vjE:h.RjWA%M_NayRQtRx]oJRPkCbbWBRjkCR+ofj]fkkDkCt7ofoyWVofoy",
    has_backdrop: true,
    backdrop_blur:
      "qjGJHOWCo#t7ozIUaejY_NoeWDj]t7RPj[RjWBWBRPa}t7j?a#WBM|ayRjWBaxofofkCbaf6aeWBV@ayoykCozWBofWBj@V@fQay",
    released_on: "2014-08-09T00:00:00",
    classification: "18+",
    sources: [
      "netflix",
      "netflix_basic",
      "amazon_prime",
      "starz",
      "roku_channel",
      "amazon_prime_free",
      "directv",
      "starz_free",
    ],
    genres: [4, 3],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 8,
    featured_services: [],
    episode_source_count: 67,
  },
  {
    id: "5d993233-3141-46bf-9b96-ec6bba041766",
    slug: "based-on-a-true-story-2023",
    content_type: "s",
    title: "Based on a True Story",
    overview:
      "A realtor, a former tennis star, and a plumber seize a unique opportunity to capitalize on America's obsession with true crime.",
    availability_pros:
      "1 episodes (13%) are available to watch free online (Peacock). 8 episodes (100%) are available to stream on a subscription service (Peacock Premium).",
    imdb_rating: 7.3,
    rt_critics_rating: null,
    rg_content_score: 74.03,
    has_poster: true,
    poster_blur: "vQFrhOnN9bW=?]xYo0R+BnxtNxoMtkoKkDbI=wWVt7WV#+NdI:ofIVofW:n%",
    has_backdrop: true,
    backdrop_blur:
      "qKE{C29G0gtRNa%1M|e.?^RioeR+V]ofs.WB2vxZxGRk$*RjS3kCY6s9sVozIpj[t6jZTdxGNHs:R*R*$%ayJBt7R*niozaeoJWX",
    released_on: "2023-06-08T00:00:00",
    classification: "18+",
    sources: ["peacock", "peacock_free"],
    genres: [10, 9],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 1,
    featured_services: [],
    episode_source_count: 0,
  },
  {
    id: "d3cb8b81-d74a-4708-8684-73022fcafe9d",
    slug: "yellowjackets-2021",
    content_type: "s",
    title: "Yellowjackets",
    overview:
      "A wildly talented high school girl soccer team becomes the (un)lucky survivors of a plane crash deep in the Canadian wilderness.",
    availability_pros:
      "1 episodes (5%) are available to watch free online (The Roku Channel, Prime Video, and Showtime Anytime). 19 episodes (100%) are available to stream on a popular subscription service (Prime Video, fuboTV, Showtime, and 1 other). 19 episodes (100%) are available to stream on a popular TV everywhere service (Showtime). 19 episodes (100%) are available to rent or buy from $1.99 on 4 services (Apple TV, Prime Video, Microsoft, and 1 other).",
    imdb_rating: 7.8,
    rt_critics_rating: 100,
    rg_content_score: 84.42,
    has_poster: true,
    poster_blur: "vKHe???a9aR*xtIUE1t7WbWBD$NG_4-pV@Rj4TWBRkWB?FWBRkj[NLt7xtoL",
    has_backdrop: true,
    backdrop_blur:
      "qGF6a%004nn6tR?u4o%2~qDiD%?bWBRks+WEM_xuM{%MRPM_-;WBRjWBs;j]RjWAtRoekCayRjt6f6Rkt7WBayayWBt7WBWAofay",
    released_on: "2021-11-14T00:00:00",
    classification: "18+",
    sources: [
      "amazon_prime",
      "fubo_tv",
      "showtime",
      "roku_channel",
      "amazon_prime_free",
      "directv",
      "showtime_free",
    ],
    genres: [3, 19],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: true,
    watchlisted: false,
    seen: false,
    season_count: 3,
    featured_services: [],
    episode_source_count: 1,
  },
  {
    id: "0656c9ea-5ca3-4e91-b449-4a369478f454",
    slug: "ted-lasso-2020",
    content_type: "s",
    title: "Ted Lasso",
    overview:
      "American college football coach Ted Lasso heads to London to manage AFC Richmond, a struggling English Premier League football team.",
    availability_pros:
      "1 episodes (3%) are available to watch free online (Apple TV+). 34 episodes (100%) are available to stream on a subscription service (Apple TV+).",
    imdb_rating: 8.8,
    rt_critics_rating: 0,
    rg_content_score: 91.22,
    has_poster: true,
    poster_blur: "vNEMeER-KmxbSCWCoiso4qogI9kCcbkEnzT09Zah-jS4eTa#ROnjRPofoyn,",
    has_backdrop: true,
    backdrop_blur:
      "qB9atD-T59O_r@I9EnVqrfs*M{Mys+tRS1g400S*w=VVkW%2#jW=XNM|x]%gR.RQt8jERNV=t8t7WCSkS%s.NLousla$RiV^RjW9",
    released_on: "2020-08-14T00:00:00",
    classification: "18+",
    sources: ["apple_tv_plus", "apple_tv_free"],
    genres: [9, 3],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: true,
    watchlisted: false,
    seen: false,
    season_count: 3,
    featured_services: [],
    episode_source_count: 34,
  },
  {
    id: "1c22bede-64d4-4134-a376-357a5244ad56",
    slug: "platonic-2023",
    content_type: "s",
    title: "Platonic",
    overview:
      "Former childhood best friends reconnect as adults and try to get past the rift that led to their falling out.",
    availability_pros:
      "1 episodes (11%) are available to watch free online (Apple TV+). 9 episodes (100%) are available to stream on a subscription service (Apple TV+).",
    imdb_rating: 7.1,
    rt_critics_rating: null,
    rg_content_score: 73.95,
    has_poster: true,
    poster_blur: "vRHw42IoIqxC}?R*wwt6D%Sh$%j@XRW=$$WUX.S2$zWCWBNGkCWCIAR*X9WW",
    has_backdrop: true,
    backdrop_blur:
      "q79ZW7NH03-o}@IpE3t7~mfiE3s:s:R+V[oe2nt5}sNHEMs;s.n#KMod$%R+Nas:oLWUtPWVoIs:R-e.oebbj?WCofs.ayayS2j]",
    released_on: "2023-05-24T00:00:00",
    classification: "18+",
    sources: ["apple_tv_plus", "apple_tv_free"],
    genres: [4, 9],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 1,
    featured_services: [],
    episode_source_count: 9,
  },
  {
    id: "5e611418-64f4-4c5e-a80d-f34e777877f4",
    slug: "alone-2015",
    content_type: "s",
    title: "Alone",
    overview:
      'Ten survival "experts" attempt to survive alone. The winner receives $500,000.',
    availability_pros:
      "100 episodes (85%) are available to watch free online (PlutoTV, Freevee, The Roku Channel, and 1 other). 111 episodes (94%) are available to stream on a popular subscription service (Netflix, Netflix Basic, Hulu, and 4 others). 107 episodes (91%) are available to stream on a TV everywhere service (History). 110 episodes (93%) are available to rent or buy from $1.99 on 7 services (iTunes, Apple TV, Google Play, and 4 others).",
    imdb_rating: 8.4,
    rt_critics_rating: 0,
    rg_content_score: 80.85,
    has_poster: true,
    poster_blur: "vSEMB_GIxtr=~V9vn$nhMwIVadadE1smj[WBSi%LkCRjbxxtflRjM|V?WBW=",
    has_backdrop: true,
    backdrop_blur:
      "qOF6FMu6IAm+9a%MxtM{xa9FM{%1M|j[s.WXEOw[RkR*jEkCoLbGJC$ya}S5slt7WWs:xujYj[WXjsofRje.-pR*jFf5bIoeWCjZ",
    released_on: "2015-06-18T00:00:00",
    classification: "16+",
    sources: [
      "netflix",
      "netflix_basic",
      "hulu_plus",
      "philo",
      "discovery_plus",
      "hoopla",
      "plutotv",
      "imdb_tv",
      "roku_channel",
      "history_tveverywhere",
      "directv",
      "history",
    ],
    genres: [11, 16],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 10,
    featured_services: [],
    episode_source_count: 11,
  },
  {
    id: "9c2d7b9a-7ded-4166-8a5c-fee2a24d801b",
    slug: "warrior-2019",
    content_type: "s",
    title: "Warrior",
    overview:
      "During the Tong Wars in the late 1800s, Ah Sahm, a martial arts prodigy from China, immigrates to San Francisco and becomes a hatchet man for the most powerful tong in Chinatown.",
    availability_pros:
      "1 episodes (4%) are available to watch free online (The Roku Channel). 24 episodes (100%) are available to stream on a popular subscription service (MAX and DIRECTV STREAM). 20 episodes (83%) are available to stream on a popular TV everywhere service (Cinemax). 20 episodes (83%) are available to rent or buy from $1.99 on 5 services (Apple TV, Google Play, Prime Video, and 2 others).",
    imdb_rating: 8.4,
    rt_critics_rating: 89,
    rg_content_score: 84.65,
    has_poster: true,
    poster_blur: "vIE1,6^ixs%1~U%1sV%1xGNH9vf+IWRkIpWC0~jFr?Rkw0sot6I;JTt6=_WW",
    has_backdrop: true,
    backdrop_blur:
      "qWDk[3-nIpNHEMI;bFfi~9xZIqoLR*RkoLoexZj[WVxZoLNHWDs:NHWVoeoes.R+R+s.M}afoea}j[ofWCafRlf7j@R+WVt6oeR+",
    released_on: "2019-04-05T00:00:00",
    classification: "18+",
    sources: ["hbo_max", "cinemax", "roku_channel", "directv"],
    genres: [3, 5],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 3,
    featured_services: [],
    episode_source_count: 0,
  },
  {
    id: "1b89956f-3a61-4779-a590-41e377e8e419",
    slug: "joe-pickett-2021",
    content_type: "s",
    title: "Joe Pickett",
    overview:
      "Follows a game warden and his family during a changing political and socioeconomic climate in a small rural town.",
    availability_pros:
      "9 episodes (53%) are available to watch free online (Prime Video). 17 episodes (100%) are available to stream on a popular subscription service (Prime Video and Paramount+). 10 episodes (59%) are available to rent or buy from $1.99 on 3 services (Apple TV, Prime Video, and Vudu).",
    imdb_rating: 7.7,
    rt_critics_rating: 0,
    rg_content_score: 75.66,
    has_poster: true,
    poster_blur: "vEE2|9?a.7jE~px[-;jYIpE19aWE9GD%IVt89Gs,xa%M-:xuRkxuE3WY%2t7",
    has_backdrop: true,
    backdrop_blur:
      "qQD]hzIVo}RPM{Io%1ad~pM{%MM{oLM{j[RjW?Rj%2M|t7V@R-RjM|WAWVWBt7WBt7t6M{WBRjWBt7oft7t7RjWBWBfRj[s;ofof",
    released_on: "2021-12-06T00:00:00",
    classification: "16+",
    sources: ["amazon_prime", "paramount_plus", "amazon_prime_free"],
    genres: [36, 3],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 2,
    featured_services: [],
    episode_source_count: 10,
  },
  {
    id: "3a9e4210-3344-4277-8cb3-6329528794e3",
    slug: "luther-2010",
    content_type: "s",
    title: "Luther",
    overview:
      "DCI John Luther is a near-genius murder detective whose brilliant mind can't always save him from the dangerous violence of his passions.",
    availability_pros:
      "20 episodes (100%) are available to watch free online (Tubi and PlutoTV). 20 episodes (100%) are available to stream on a subscription service (BritBox and Hoopla). 20 episodes (100%) are available to rent or buy from $1.99 on 6 services (iTunes, Apple TV, Google Play, and 3 others).",
    imdb_rating: 8.4,
    rt_critics_rating: 88,
    rg_content_score: 89.77,
    has_poster: true,
    poster_blur: "vHCFYbR%tlad{MRjIpaz*|kWM{of^OWA%2jaEgRjbbWBAYt7NGkCF_ogr=a}",
    has_backdrop: true,
    backdrop_blur:
      "q27LT9ZL0Xel00.S+sKQ00Rm,k%h?wIAO[v}8_%#,9IV.RH@9b-6?GMdF4bIDj-:=^E+M_R6xZyCMxg3x]MyO[xW-pM|R5M}Io$%",
    released_on: "2010-05-04T00:00:00",
    classification: "18+",
    sources: ["britbox", "hoopla", "tubi_tv", "plutotv"],
    genres: [3, 10],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 5,
    featured_services: [],
    episode_source_count: 0,
  },
  {
    id: "b3c5e2b7-1f06-4073-97ba-4fe30bc1ff63",
    slug: "young-sheldon-2017",
    content_type: "s",
    title: "Young Sheldon",
    overview:
      "Meet a child genius named Sheldon Cooper (already seen as an adult in The Big Bang Theory (2007)) and his family. Some unique challenges face Sheldon, who is socially impaired.",
    availability_pros:
      "8 episodes (6%) are available to watch free online (Prime Video and CBS). 128 episodes (100%) are available to stream on a popular subscription service (Prime Video, MAX, Paramount+, and 3 others). 36 episodes (28%) are available to stream on a popular TV everywhere service (TBS and CBS). 128 episodes (100%) are available to rent or buy from $1.80 on 7 services (iTunes, Apple TV, Google Play, and 4 others).",
    imdb_rating: 7.6,
    rt_critics_rating: 0,
    rg_content_score: 84.88,
    has_poster: true,
    poster_blur: "vDLW69Rr00Oa3s%2$_kW00A@~WNu,.a2$cR%totODi+[R4Fx-Ws8Q:I[yC-o",
    has_backdrop: true,
    backdrop_blur:
      "q8FE}=00V=.A}=0~MI?H4Tt,?H9srrbvkWsA3r+FnTyX9G,opcIo5;=FkrDi%#wIE2ba-:H?lT;P4-.SMexu?HWY9Y-Wx]E1wIo~",
    released_on: "2017-09-25T00:00:00",
    classification: "7+",
    sources: [
      "amazon_prime",
      "hbo_max",
      "paramount_plus",
      "fubo_tv",
      "tbs",
      "amazon_prime_free",
      "cbs_tveverywhere",
      "cbs",
      "directv",
      "tvision",
    ],
    genres: [9, 8],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 7,
    featured_services: [],
    episode_source_count: 1,
  },
  {
    id: "03cae40a-26d8-4ab4-82be-d8b9a8f3d1dc",
    slug: "foundation-2020",
    content_type: "s",
    title: "Foundation",
    overview:
      "A complex saga of humans scattered on planets throughout the galaxy all living under the rule of the Galactic Empire.",
    availability_pros:
      "1 episodes (10%) are available to watch free online (Apple TV+). 10 episodes (100%) are available to stream on a subscription service (Apple TV+). Episodes coming soon to Apple TV+ on July 13th, 2023 (PDT).",
    imdb_rating: 7.4,
    rt_critics_rating: 70,
    rg_content_score: 83.63,
    has_poster: true,
    poster_blur: "vuK^]SW;yDR+~qbI-=R*9Fj]%Mj=VsoJRPoexvjsn$oLS5WXt7f6s,jZR*j[",
    has_backdrop: true,
    backdrop_blur:
      "qbGSJ.M{00xuQ,x]-:Ip?wRjM{s,I9xt%fNHD%fl-;WAIoofjboespj?WVWEozjsRPs:g3ayn$j[R+j[t6ayaya}ofjsaea}bbf6",
    released_on: "2021-09-24T00:00:00",
    classification: "16+",
    sources: ["apple_tv_plus", "apple_tv_free"],
    genres: [3, 13],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 2,
    featured_services: [],
    episode_source_count: 10,
  },
  {
    id: "2dac2373-ca3e-4da6-bb0a-0cf26a2dd6ca",
    slug: "fear-the-walking-dead-2015",
    content_type: "s",
    title: "Fear the Walking Dead",
    overview:
      "A Walking Dead spinoff set in Los Angeles, California. Follows two families who must band together to survive the undead apocalypse.",
    availability_pros:
      "2 episodes (2%) are available to watch free online (The Roku Channel and Prime Video). 27 episodes (25%) are available to stream on a popular subscription service (Prime Video, Philo, AMC+, and 2 others). 76 episodes (70%) are available to stream on a popular TV everywhere service (AMC). 107 episodes (98%) are available to rent or buy from $1.99 on 7 services (iTunes, Apple TV, Google Play, and 4 others).",
    imdb_rating: 6.8,
    rt_critics_rating: 75,
    rg_content_score: 84.33,
    has_poster: true,
    poster_blur: "v59tbp04s;EM{.E2%vIXKt-nIE%K04?YWB%K4sxZtNoJ.LM~VxobDUSetORk",
    has_backdrop: true,
    backdrop_blur:
      "q57e5-9J0#-nxZIW-nbY~SD-IpofspRks:oLEeox?EE4g1xsIqs:EMs.-nIXRlsWNHodR+WVt6ovWobHodafovWCRUs.WCWDWDWC",
    released_on: "2015-08-23T00:00:00",
    classification: "18+",
    sources: [
      "amazon_prime",
      "philo",
      "amc_plus",
      "amc",
      "roku_channel",
      "amazon_prime_free",
      "directv",
      "tvision",
    ],
    genres: [3, 19],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 8,
    featured_services: [],
    episode_source_count: 1,
  },
  {
    id: "52a2819d-b646-4c34-84ed-679f6be20a4b",
    slug: "schitts-creek-2015",
    content_type: "s",
    title: "Schitt's Creek",
    overview:
      "After being a victim of fraud, Johnny Rose and his family go from extremely wealthy to penniless overnight. The only asset left to them is a small, unsophisticated town: Schitt's Creek. They relocate there. Culture shock ensues.",
    availability_pros:
      "81 episodes (100%) are available to watch free online (Freevee). 80 episodes (99%) are available to stream on a popular subscription service (Hulu, Philo, and DIRECTV STREAM). 81 episodes (100%) are available to rent or buy from $1.99 on 6 services (iTunes, Apple TV, Google Play, and 3 others).",
    imdb_rating: 8.5,
    rt_critics_rating: 50,
    rg_content_score: 88.85,
    has_poster: true,
    poster_blur: "vCJQQGE+~C58?bE10f%215V@V@Rjt.~B$%oL02IUIoofNdaextWBt7S$t7S4",
    has_backdrop: true,
    backdrop_blur:
      "q8JGp70h?F0000%00L?H]~575S%L^*E2?HE1009GX9~W?G%M-oof?u?HIVsoNHf+R*ofx]ENw{M{-oRPozI:xuxbt7IU%0IVNGNI",
    released_on: "2015-01-13T00:00:00",
    classification: "16+",
    sources: ["hulu_plus", "philo", "imdb_tv", "directv"],
    genres: [9],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 6,
    featured_services: [],
    episode_source_count: 0,
  },
  {
    id: "a094b08e-3bf4-4364-8c88-cbd86da0c1ec",
    slug: "endeavour-2012",
    content_type: "s",
    title: "Endeavour",
    overview:
      "Set from 1965 into the 1970s, the show follows Endeavour Morse in his early years as a police constable. Working alongside his senior partner DI Fred Thursday, Morse engages in a number of investigations around Oxford.",
    availability_pros:
      "35 episodes (88%) are available to watch free online (Prime Video and PBS). 37 episodes (93%) are available to stream on a popular subscription service (Prime Video and DIRECTV STREAM). 35 episodes (88%) are available to rent or buy from $1.99 on 6 services (iTunes, Apple TV, Google Play, and 3 others).",
    imdb_rating: 8.6,
    rt_critics_rating: 86,
    rg_content_score: 84.96,
    has_poster: true,
    poster_blur: "v7CF#H?w9]}?m*ITxa-o00Di$*9[B=?bEM4:IVNHxaoLROMx-Uoz-9xaIot6",
    has_backdrop: true,
    backdrop_blur:
      "q7DSH_0f00^P%#kD#k0K~8D$%MNe9F%2%MS20#-U^PE+a0bvIo^O.9n$Mwt7t7S$V@nO%MM{t8S4E0%1o}I:^*WBE2tRxGWVWVae",
    released_on: "2012-01-02T00:00:00",
    classification: "16+",
    sources: ["amazon_prime", "amazon_prime_free", "directv", "pbs"],
    genres: [10, 3],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 9,
    featured_services: [],
    episode_source_count: 35,
  },
  {
    id: "4af0beb4-717c-4fd4-bf47-223cf0428c60",
    slug: "american-gladiators-1989",
    content_type: "s",
    title: "American Gladiators",
    overview:
      "The teams compete in such events as Power Ball, Assault, The Wall and Hang Tough. The Eliminator round decides the winner of the tournament.",
    availability_pros:
      "49 episodes (27%) are available to watch free online (The Roku Channel).",
    imdb_rating: 6.5,
    rt_critics_rating: null,
    rg_content_score: 71.92,
    has_poster: true,
    poster_blur: "vPJHH=NF.8oM_3of-=oL_Nt7%ft7xbofkqR%^*e-W=og$*V@ozWX-oRjozjY",
    has_backdrop: true,
    backdrop_blur:
      "qMJ7amD$4.o#RjkWIVxt~XWCInslIVt7s,S5I=oKNtNGaJayxboJV[NGxukCbFozV@xut5ayM|t6xuj]V@WXRkoIR*WCt7jYR+jF",
    released_on: "1989-01-01T00:00:00",
    classification: "7+",
    sources: ["roku_channel"],
    genres: [16, 5],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 8,
    featured_services: [],
    episode_source_count: 0,
  },
  {
    id: "37346805-f194-4c9a-aa9b-eb52f2323889",
    slug: "mad-men-2007",
    content_type: "s",
    title: "Mad Men",
    overview:
      "A drama about one of New York's most prestigious ad agencies at the beginning of the 1960s, focusing on one of the firm's most mysterious but extremely talented ad executives, Donald Draper.",
    availability_pros:
      "92 episodes (98%) are available to watch free online (Freevee). 92 episodes (98%) are available to stream on a subscription service (AMC+, AMC Premiere, and DIRECTV STREAM). 94 episodes (100%) are available to rent or buy from $1.99 on 6 services (iTunes, Apple TV, Prime Video, and 3 others).",
    imdb_rating: 8.7,
    rt_critics_rating: 94,
    rg_content_score: 91.89,
    has_poster: true,
    poster_blur: "v~K-UqVsoft7~qbHayoftRozWBWBn%n%f6WBnie.ofayI:bboff6f+a|WBj[",
    has_backdrop: true,
    backdrop_blur:
      "q~IrELWBt7xut7t7j[WB~qayayt7t7ofj[WBxuofRjWBayWBayayRjofWBWBWBWBayfQWBayt7j[WBj[j[j[j[ayofj[ayj[j[j[",
    released_on: "2007-07-19T00:00:00",
    classification: "16+",
    sources: ["amc_plus", "amc_premiere", "imdb_tv", "directv"],
    genres: [3],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 7,
    featured_services: [],
    episode_source_count: 0,
  },
  {
    id: "e41804e6-9206-4265-a13a-5882c78ab365",
    slug: "1923-2022",
    content_type: "s",
    title: "1923",
    overview:
      "The Duttons face a new set of challenges in the early 20th century, including the rise of Western expansion, Prohibition, and the Great Depression.",
    availability_pros:
      "1 episodes (13%) are available to watch free online (PlutoTV). 8 episodes (100%) are available to stream on a subscription service (Paramount+). 8 episodes (100%) are available to rent or buy from $1.99 on 4 services (Apple TV, Prime Video, Microsoft, and 1 other).",
    imdb_rating: 8.4,
    rt_critics_rating: null,
    rg_content_score: 80.11,
    has_poster: true,
    poster_blur: "vLF=w4=_?Z-U~pt7.8ju~p-oW=oftR-nRPW=9ZjsM|NcozRkRPoeIVNGa#ay",
    has_backdrop: true,
    backdrop_blur:
      "qJF}fa02--%1M|I;Wqw]~oDkNx-nV[R-s.WCI;jFRkW;t5s.oebHRjShn~R+bboJjZoeWBkBWXs,R*W=aejaoejGkBWCn%bbWVo0",
    released_on: "2022-12-18T00:00:00",
    classification: "18+",
    sources: ["paramount_plus", "plutotv"],
    genres: [3, 36],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 2,
    featured_services: [],
    episode_source_count: 0,
  },
  {
    id: "4bfd8d36-016a-4eb7-8bd8-aaff870a7d8e",
    slug: "shameless-2011",
    content_type: "s",
    title: "Shameless",
    overview:
      "A scrappy, feisty, fiercely loyal Chicago family makes no apologies.",
    availability_pros:
      "1 episodes (1%) are available to watch free online (Showtime Anytime). 137 episodes (98%) are available to stream on a popular subscription service (Netflix, Netflix Basic, fuboTV, and 2 others). 96 episodes (69%) are available to stream on a popular TV everywhere service (Showtime). 139 episodes (99%) are available to rent or buy from $1.99 on 6 services (iTunes, Apple TV, Google Play, and 3 others).",
    imdb_rating: 8.6,
    rt_critics_rating: 82,
    rg_content_score: 91.93,
    has_poster: true,
    poster_blur: "vYF55NV@xBnh}@WZs;s8TJkCR+xGOYofR*t7NJf+oLWYTJofjZR-WBxZbbSN",
    has_backdrop: true,
    backdrop_blur:
      "qRFhVS%1M{nhxYrswIt7~Xxtr?xCoeWYslxaKjt7Vtxat7WXxGo#OtkWRjW=W.oeSgNetlobe:S5NaaeR+s.OsxCniR-jYjFsTs:",
    released_on: "2011-01-09T00:00:00",
    classification: "18+",
    sources: [
      "netflix",
      "netflix_basic",
      "fubo_tv",
      "showtime",
      "directv",
      "showtime_free",
    ],
    genres: [9, 3],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 11,
    featured_services: [],
    episode_source_count: 134,
  },
  {
    id: "396f0df2-0700-40e9-80b1-801643098fb5",
    slug: "invasion-2021",
    content_type: "s",
    title: "Invasion",
    overview:
      "Earth is visited by an alien species that threatens humanity's existence. Events unfold in real time through the eyes of five ordinary people across the globe as they struggle to make sense of the chaos unraveling around them.",
    availability_pros:
      "1 episodes (10%) are available to watch free online (Apple TV+). 10 episodes (100%) are available to stream on a subscription service (Apple TV+).",
    imdb_rating: 6,
    rt_critics_rating: 47,
    rg_content_score: 77.02,
    has_poster: true,
    poster_blur: "vC9In+t+y;o{8#j]jIbbMyo|VtoywZkWtkkC8}aLMeRQ.6VtRkjIR8V]tPV[",
    has_backdrop: true,
    backdrop_blur:
      "qFA.0k?[.6%Lx@jvtkX7%L.kx[x@aLt6tQoyDltQoykCtQjaaLt6yCx@t6VuVtVuafV[?sxtxasAMyV[WCRkx@oyx[j[V[WCV[RR",
    released_on: "2021-10-22T00:00:00",
    classification: "18+",
    sources: ["apple_tv_plus", "apple_tv_free"],
    genres: [13, 3],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: true,
    watchlisted: false,
    seen: false,
    season_count: 2,
    featured_services: [],
    episode_source_count: 10,
  },
  {
    id: "a9f4f694-09b0-47c0-be5e-6a8b0032a08e",
    slug: "lost-2004",
    content_type: "s",
    title: "Lost",
    overview:
      "The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.",
    availability_pros:
      "120 episodes (97%) are available to watch free online (Freevee). 122 episodes (98%) are available to stream on a popular subscription service (Hulu). 121 episodes (98%) are available to rent or buy from $1.99 on 6 services (iTunes, Apple TV, Google Play, and 3 others).",
    imdb_rating: 8.3,
    rt_critics_rating: 85,
    rg_content_score: 92.72,
    has_poster: true,
    poster_blur: "vD8rj$tlRPWBX-tRR5ayQmjZaebH.mV@o}kC00RjofofHXRjtRaeXRV@o}kC",
    has_backdrop: true,
    backdrop_blur:
      "https://is3-ssl.mzstatic.com/image/thumb/HeurDZOe18gNeuie5-QyRw/3840x2160.jpg",
    released_on: "2004-09-22T00:00:00",
    classification: "16+",
    sources: ["hulu_plus", "imdb_tv"],
    genres: [5, 3],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 6,
    featured_services: [],
    episode_source_count: 0,
  },
  {
    id: "62800b84-d2c1-4872-9f98-8b8bfea7daa7",
    slug: "shrinking-2023",
    content_type: "s",
    title: "Shrinking",
    overview:
      "A grieving therapist starts to tell his clients exactly what he thinks. Ignoring his training and ethics, he finds himself making huge changes to people's lives - including his own.",
    availability_pros:
      "1 episodes (10%) are available to watch free online (Apple TV+). 10 episodes (100%) are available to stream on a subscription service (Apple TV+).",
    imdb_rating: 8,
    rt_critics_rating: null,
    rg_content_score: 79.22,
    has_poster: true,
    poster_blur: "veIi2oIUO?t7?^sAn$ShI;kWnOsmoJShoyiwWqsoWBbbxZniX8ShjZWBaeof",
    has_backdrop: true,
    backdrop_blur:
      "qPHfn,9F%~aKicS2X9xa_NM|Mxt7ofn%kCWBX9oLjER+g3soV@X8WXj[jZjZf+WWjZn%jsWVj[oLWVX8oJe-bIfkjZaybHj[e.j[",
    released_on: "2023-01-27T00:00:00",
    classification: "18+",
    sources: ["apple_tv_plus", "apple_tv_free"],
    genres: [9, 3],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: true,
    watchlisted: false,
    seen: false,
    season_count: 2,
    featured_services: [],
    episode_source_count: 10,
  },
  {
    id: "0a041459-2078-4d16-b3d2-9cd3b1309a9e",
    slug: "shiny-happy-people-duggar-family-secrets-2023",
    content_type: "s",
    title: "Shiny Happy People: Duggar Family Secrets",
    overview:
      "Docuseries exploring the truth beneath the surface of reality TV's mega-family, The Duggars.",
    availability_pros:
      "2 episodes (50%) are available to watch free online (Freevee). 4 episodes (100%) are available to stream on a popular subscription service (Prime Video).",
    imdb_rating: 7.6,
    rt_critics_rating: null,
    rg_content_score: 73.1,
    has_poster: true,
    poster_blur: "vSE3xVWBIUj]t:V[RPj[ITayoLWA^+RjofjZJoRPjZt7adaxjZbFxFR*oKjZ",
    has_backdrop: true,
    backdrop_blur:
      "qjDmaObHXToLbvjuoLoL_4ayW=ofbIayj[oLM~f6RPs:e.WBj[kBE1j[VskBjFWBj[fkW=j[j?ayoeaej[a}oNazofa{ofjsf6f8",
    released_on: "2023-05-18T00:00:00",
    classification: null,
    sources: ["amazon_prime", "imdb_tv"],
    genres: [11],
    on_services: true,
    on_free: true,
    on_rent_purchase: false,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 1,
    featured_services: [],
    episode_source_count: 4,
  },
  {
    id: "cb95f4e2-d119-4a1c-99cd-bda75ac33e32",
    slug: "sherlock-2010",
    content_type: "s",
    title: "Sherlock",
    overview:
      "The quirky spin on Conan Doyle's iconic sleuth pitches him as a \"high-functioning sociopath\" in modern-day London. Assisting him in his investigations: Afghanistan War vet John Watson, who's introduced to Holmes by a mutual acquaintance.",
    availability_pros:
      "13 episodes (72%) are available to watch free online (Crackle). 13 episodes (72%) are available to stream on a subscription service (Philo). 16 episodes (89%) are available to rent or buy from $1.99 on 7 services (iTunes, Apple TV, Google Play, and 4 others).",
    imdb_rating: 9.1,
    rt_critics_rating: 78,
    rg_content_score: 96.74,
    has_poster: true,
    poster_blur: "v45#-EadD%Ioo~aeoING4nWBtRt7-.WBM|xu01fPxut74ot7xtae~pxuIURP",
    has_backdrop: true,
    backdrop_blur:
      "q26*ag4T?w9ZWTofoInib_i_xvt6WAoJRjt6W,t6V@%2a$t6NGWVMxt7M_oz%2bIt7R*Nwn%aeM{kCt7xat7xvRjofofbFoLs:oM",
    released_on: "2010-07-22T00:00:00",
    classification: "16+",
    sources: ["philo", "crackle"],
    genres: [3, 23],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 4,
    featured_services: [],
    episode_source_count: 0,
  },
  {
    id: "d780bb23-3013-4421-8acc-2758b745205d",
    slug: "the-blacklist-2013",
    content_type: "s",
    title: "The Blacklist",
    overview:
      "A new FBI profiler, Elizabeth Keen, has her entire life uprooted when a mysterious criminal, Raymond Reddington, who has eluded capture for decades, turns himself in and insists on speaking only to her.",
    availability_pros:
      "7 episodes (3%) are available to watch free online (Peacock and NBC). 202 episodes (94%) are available to stream on a popular subscription service (Netflix, Netflix Basic, Peacock Premium, and 3 others). 5 episodes (2%) are available to stream on a TV everywhere service (NBC). 216 episodes (100%) are available to rent or buy from $0.00 on 7 services (iTunes, Apple TV, Google Play, and 4 others). Episodes coming soon to Peacock Premium on July 20th, 2023 (PDT).",
    imdb_rating: 8,
    rt_critics_rating: 91,
    rg_content_score: 90.12,
    has_poster: true,
    poster_blur: "vcH-S_%M-pxu*J%M%gRjWB-p-;IU+^NuxaWVPURjR*xu=|aKaeWBs:I:ofM{",
    has_backdrop: true,
    backdrop_blur:
      "q87vZLODB9,E5+Na{}S2xGWVR*fQofsoniWp#SS2R*wxOrj[niSgSgW;n%n%o1jZS2j[J,aywdbHn%oLK4fkS2a|soo1WVayj[o1",
    released_on: "2013-09-23T00:00:00",
    classification: "16+",
    sources: [
      "netflix",
      "netflix_basic",
      "peacock",
      "fubo_tv",
      "peacock_free",
      "nbc_tveverywhere",
      "directv",
      "nbc",
      "tvision",
    ],
    genres: [3, 10],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 10,
    featured_services: [],
    episode_source_count: 196,
  },
  {
    id: "013d2935-9a8b-4882-822e-4a3fe581caff",
    slug: "the-walking-dead-2010",
    content_type: "s",
    title: "The Walking Dead",
    overview:
      "Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.",
    availability_pros:
      "83 episodes (47%) are available to watch free online (PlutoTV). 177 episodes (100%) are available to stream on a popular subscription service (Netflix, AMC+, AMC Premiere, and 1 other). 151 episodes (85%) are available to stream on a popular TV everywhere service (AMC). 177 episodes (100%) are available to rent or buy from $1.99 on 7 services (iTunes, Apple TV, Google Play, and 4 others).",
    imdb_rating: 8.1,
    rt_critics_rating: 80,
    rg_content_score: 93.64,
    has_poster: true,
    poster_blur: "vVJ@my~U^*WX^*4;afxt~o%KkCV[NbV[RkR*E2M|M|fPocofWBWCaya#oLoe",
    has_backdrop: true,
    backdrop_blur:
      "q38NtVtk-WNc9Gbb4;E2y=ni57niWBxGxat600M|rXkB?GIo%1t7n4n%sCt7I;RkIoj[xZbZNHWWM|%2r?W;M|ofW;kCxGe.oyay",
    released_on: "2010-10-31T00:00:00",
    classification: "18+",
    sources: [
      "netflix",
      "amc_plus",
      "amc_premiere",
      "amc",
      "plutotv",
      "directv",
    ],
    genres: [3, 19],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: true,
    watchlisted: false,
    seen: false,
    season_count: 11,
    featured_services: [],
    episode_source_count: 177,
  },
  {
    id: "be59de54-5c3b-469c-9ef0-44b5f1af3cbb",
    slug: "south-park-1997",
    content_type: "s",
    title: "South Park",
    overview:
      "Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.",
    availability_pros:
      "34 episodes (10%) are available to watch free online (Comedy Central and South Park). 324 episodes (100%) are available to stream on a popular subscription service (MAX, Paramount+, Philo, and 3 others). 10 episodes (3%) are available to stream on a TV everywhere service (Comedy Central). 321 episodes (99%) are available to rent or buy from $1.99 on 7 services (iTunes, Apple TV, Google Play, and 4 others).",
    imdb_rating: 8.7,
    rt_critics_rating: 80,
    rg_content_score: 92.93,
    has_poster: true,
    poster_blur: "v-LOH0WXkWsA5lS3WWn$?wR*jFj?oJafoebbNbWVjFX8ivWBjYfkxYWXbao2",
    has_backdrop: true,
    backdrop_blur:
      "q59QHm%L009H$]?Gx^IpbXNGW@%2%0R%EMWV00RQ~o%fNgIVMxxF?IxuROIU9vkX-oxY5lS~#+rXWGbbo|kVH?nOoyO?tS$eRiIX",
    released_on: "1997-08-13T00:00:00",
    classification: "16+",
    sources: [
      "hbo_max",
      "paramount_plus",
      "philo",
      "fubo_tv",
      "comedycentral_tveverywhere",
      "comedy",
      "directv",
      "tvision",
      "southpark",
    ],
    genres: [9, 6],
    on_services: true,
    on_free: true,
    on_rent_purchase: true,
    user_rating: null,
    tracking: false,
    watchlisted: false,
    seen: false,
    season_count: 30,
    featured_services: [],
    episode_source_count: 0,
  },
];
