const movies = {
  results: [
    {
      id: "c77578d5-2736-4da6-9e8e-269509c5ef61",
      slug: "avatar-the-way-of-water-2022",
      content_type: "m",
      title: "Avatar: The Way of Water",
      overview:
        "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
      availability_pros:
        "Available to stream on a popular subscription service (MAX, Disney+, and DIRECTV STREAM). Available to rent or buy from $19.99 on 4 services (Apple TV, Prime Video, Microsoft, and 1 other).",
      imdb_rating: 7.7,
      rt_critics_rating: null,
      rg_content_score: 87.53,
      has_poster: true,
      poster_blur:
        "vNB{}zWUD,xtD*ayt5WW0Mj[${Rk~Tj?M}t6ocaekDW=59j]xZRk$dkCWYs-",
      has_backdrop: true,
      backdrop_blur:
        "qnF~jc9GMy%LM{f9oeR*~pE1R*ogaeofWBae%MRjkBRkt7j@V[ofxuayaeWBogV@aykCogj[WUj[j[WBj[WCbIaeaeofWVjZj[WB",
      released_on: "2022-12-14T00:00:00",
      classification: "13+",
      sources: ["hbo_max", "disney_plus", "directv"],
      genres: [5, 13],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "a2eb8042-7b35-46ed-a7e7-71bddc49cabb",
      slug: "air-jordan",
      content_type: "m",
      title: "Air",
      overview:
        "Follows the history of sports marketing executive Sonny Vaccaro, and how he led Nike in its pursuit of the greatest athlete in the history of basketball, Michael Jordan.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video).",
      imdb_rating: 7.5,
      rt_critics_rating: null,
      rg_content_score: 79.98,
      has_poster: true,
      poster_blur:
        "vSMs=%0KIpae00t7i_xt_3.8xtaK%MD%ocR+.Ss9%2SO%1%MNGIU_NRPIBxu",
      has_backdrop: true,
      backdrop_blur:
        "qsLz%6x^~q?bt7n$RjE1M{%MRPWVW=jFayofxuRjoeRkjZofRkofozoLayRjt7R*jZoLxuWBRjt7WVRjt7aytQRjkCaejZkCWBa}",
      released_on: "2023-07-02T00:00:00",
      classification: "18+",
      sources: ["amazon_prime"],
      genres: [3, 17],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "65f10856-6be7-4f0a-b41e-eca306ae7e13",
      slug: "extraction-2",
      content_type: "m",
      title: "Extraction 2",
      overview:
        "After barely surviving his grievous wounds from his mission in Dhaka, Bangladesh, Tyler Rake is back, and his team is ready to take on their next mission.",
      availability_pros:
        "Available to stream on a popular subscription service (Netflix and Netflix Basic).",
      imdb_rating: 8.1,
      rt_critics_rating: null,
      rg_content_score: 66.99,
      has_poster: true,
      poster_blur:
        "vOD9*jE1X9Z~%%t8kDaJbwt8f5aybIWEWBbIbvRjn~bcx]slRiogITxaozR*",
      has_backdrop: true,
      backdrop_blur:
        "q9Cis}01E04os.?aI?RQ~WRjjF4.xZxtRke.01~BE2-:M|IV%1Rj4o-pRj?b9tRP%LNG4ot6-oI=-pIpIU%MogM_fltR%1R-M{of",
      released_on: "2023-06-13T00:00:00",
      classification: "18+",
      sources: ["netflix", "netflix_basic"],
      genres: [5, 32],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "0aca9d35-ed0b-43ac-b31e-5150ec304b12",
      slug: "creed-iii-2022",
      content_type: "m",
      title: "Creed III",
      overview:
        "Adonis has been thriving in both his career and family life, but when a childhood friend and former boxing prodigy resurfaces, the face-off is more than just a fight.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video). Available to rent or buy from $5.99 on 4 services (Apple TV, Prime Video, Microsoft, and 1 other).",
      imdb_rating: 6.9,
      rt_critics_rating: null,
      rg_content_score: 75.1,
      has_poster: true,
      poster_blur:
        "vLDvf%D%D%NG?wD%?HR*t8D%x]Rj%2M{NaM{4.WB-pR*-pWVIobbxuofofkW",
      has_backdrop: true,
      backdrop_blur:
        "qAB.=m%z7y=|}Zt,yD%M_M%L=yWANaxuS#%2?]-oxZxtS4-oxatQt+xtxGs:R*oyR*ni-oWUNGbur?bFayR*wdW;SfoeoLoeWBR*",
      released_on: "2023-03-01T00:00:00",
      classification: "13+",
      sources: ["amazon_prime"],
      genres: [3, 5],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "ff8e0e6c-820c-4eb4-9e3a-36eb4665dbd0",
      slug: "a-man-called-otto-2022",
      content_type: "m",
      title: "A Man Called Otto",
      overview:
        "Otto is a grump who's given up on life following the loss of his wife and wants to end it all. When a young family moves in nearby, he meets his match in quick-witted Marisol, leading to a friendship that will turn his world around.",
      availability_pros:
        "Available to stream on a popular subscription service (Netflix). Available to rent or buy from $4.99 on 3 services (Apple TV, Prime Video, and Microsoft).",
      imdb_rating: 7.5,
      rt_critics_rating: null,
      rg_content_score: 79.7,
      has_poster: true,
      poster_blur:
        "vpFj4yR.k?oe?wNdSiaytRRkRkWCxuofM{oeozn~RPoeRjoeofj[Rlayj]jZ",
      has_backdrop: true,
      backdrop_blur:
        "qeFZ{N?YTzNGa0ofShWX.TtRIVS5nho0bvWBRjR*Vsa#t7oej[WCShe.t7oIX9azV@f+R+bIo0s:j@ayWAWBkWWBWBWBj[oeofjt",
      released_on: "2022-12-25T00:00:00",
      classification: "13+",
      sources: ["netflix"],
      genres: [3, 9],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "a2ca3ab3-a3d4-40bf-ad78-e03af45502b7",
      slug: "missing-2023",
      content_type: "m",
      title: "Missing",
      overview:
        "After her mother goes missing, a young woman tries to find her from home, using tools available to her online.",
      availability_pros:
        "Available to stream on a popular subscription service (Netflix). Available to rent or buy from $5.99 on 3 services (Apple TV, Prime Video, and Microsoft).",
      imdb_rating: 7.1,
      rt_critics_rating: null,
      rg_content_score: 76.24,
      has_poster: true,
      poster_blur:
        "vrFP~p?vVqoz?wx[jDogMwRObJWXk8bGV_V@a}WEWEocM|RQayocj[kCWUV[",
      has_backdrop: true,
      backdrop_blur:
        "q9E28?B:5mHX0MwI?u_2?^xbrX014:s8%2tlK*=xNGEf^JTJf,w}%2ELniNGxta}NHRPo|V@w{NHbdxGt5ELwbWBNdt7WY%1smM|",
      released_on: "2023-01-20T00:00:00",
      classification: "13+",
      sources: ["netflix"],
      genres: [3, 23],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "e626a4c5-3bf4-42c8-9029-374bb214af99",
      slug: "flamin-hot-2023",
      content_type: "m",
      title: "Flamin' Hot",
      overview:
        "This is the inspiring true story of Richard Montañez who, as a Frito Lay janitor, disrupted the food industry by channeling his Mexican heritage to turn Flamin' Hot Cheetos from a snack into an iconic global pop culture phenomenon.",
      availability_pros:
        "Available to stream on a popular subscription service (Disney+ and Hulu).",
      imdb_rating: 6.9,
      rt_critics_rating: null,
      rg_content_score: 70.44,
      has_poster: true,
      poster_blur:
        "vlN%[q$_Vaog~8kRNHoM5UV[S|WFRSrrofNL#SS#S5RkNHbvofnhaLs.oyWU",
      has_backdrop: true,
      backdrop_blur:
        "qXGbYX.8%fxsM|R%awRk~Vt7S5RjM{oft7bHxtbFWYWFoft7s:j@o}W=oLj]jZoeR*bItlkEjGs+afaybaj]o}f,WBoLn$a#oeoJ",
      released_on: "2023-06-09T00:00:00",
      classification: "13+",
      sources: ["disney_plus", "hulu_plus"],
      genres: [3, 7],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "d4236156-c88b-478f-8d36-e132ac883bda",
      slug: "antman-and-the-wasp-quantumania-2023",
      content_type: "m",
      title: "Ant-Man and the Wasp: Quantumania",
      overview:
        "Scott Lang and Hope Van Dyne are dragged into the Quantum Realm, along with Hope's parents and Scott's daughter Cassie. Together they must find a way to escape, but what secrets is Hope's mother hiding? And who is the mysterious Kang?",
      availability_pros:
        "Available to stream on a popular subscription service (Disney+). Available to rent or buy from $5.99 on 4 services (Apple TV, Prime Video, Microsoft, and 1 other).",
      imdb_rating: 6.1,
      rt_critics_rating: null,
      rg_content_score: 76.3,
      has_poster: true,
      poster_blur:
        "vND9Y[oiI{I:MxV?NER%KnRiWBxWI^WB-qs;9tn+wajcx{kCbckCeTj]W8a}",
      has_backdrop: true,
      backdrop_blur:
        "q26jd#0f0z}@aLE2-oe:WqayI;$*s:sn9]-A02}@^P0zxZ-VE2xZjZjt-AJ7I:Na}sEM^jEL9]~AEMM|%LIp-UNbS2Ip-Bs:EfxZ",
      released_on: "2023-02-15T00:00:00",
      classification: "13+",
      sources: ["disney_plus"],
      genres: [5, 26],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "78009c13-fe3d-4e49-9a1e-25fbbabf7817",
      slug: "culpa-mia-2023",
      content_type: "m",
      title: "My Fault",
      overview:
        "Noah has to leave her town, boyfriend and friends behind and move into the mansion of her mother's new rich husband. There she meets Nick, her new stepbrother. They fall madly in love in secret.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video).",
      imdb_rating: 6.3,
      rt_critics_rating: null,
      rg_content_score: 68.33,
      has_poster: true,
      poster_blur:
        "vGDbvP=a02OY~U-nR6NH0Lx]~AiwIUR-tR$yx]V[IpxaNzoKjDNbIVkCxZR+",
      has_backdrop: true,
      backdrop_blur:
        "q35E?WJW00?G}+9tJ;,o?JI[E1=_r;56%4=|9vR.={$d9tIp-q%3s,t8NdITxZ-pI;9_jEo#X9NFs,xaNGNdENWV-Vs:InNGxb$*",
      released_on: "2023-05-08T00:00:00",
      classification: null,
      sources: ["amazon_prime"],
      genres: [3, 4],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "d8acf561-e190-4c1b-87bd-173ef42f2394",
      slug: "tiptoes-2003",
      content_type: "m",
      title: "Tiptoes",
      overview: "The story of a peculiar love triangle involving two brothers.",
      availability_pros:
        "Available to watch free online (Tubi and The Roku Channel). Available to stream on a popular subscription service (Prime Video). Available to rent or buy from $2.99 on 7 services (iTunes, Apple TV, Google Play, and 4 others).",
      imdb_rating: 4.3,
      rt_critics_rating: 0,
      rg_content_score: 58.85,
      has_poster: true,
      poster_blur:
        "v~MHDOoLofs:_Njtf7WCt7ayjtoea0jZWVayNGj[oea#xvWBWCoexuoLf6WC",
      has_backdrop: true,
      backdrop_blur:
        "qKEyJTMy~qE2R$xuD$-p%NWBbc?coM-pD*WA%h-;xa%MRioej@M_xvofs:xvR+RkRiRP%MWBWAt7ofj[aeayxaRjWBa~t7jboLf7",
      released_on: "2004-01-16T00:00:00",
      classification: "18+",
      sources: ["amazon_prime", "tubi_tv", "roku_channel"],
      genres: [3, 4],
      on_services: true,
      on_free: true,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "2b222a79-d0fc-4c6b-b31b-44780d865bc0",
      slug: "interstellar-2014",
      content_type: "m",
      title: "Interstellar",
      overview:
        "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video, Paramount+, fuboTV, and 3 others). Available to stream on a popular TV everywhere service (Epix and FXNOW). Available to rent or buy from $2.99 on 6 services (iTunes, Apple TV, Google Play, and 3 others).",
      imdb_rating: 8.6,
      rt_critics_rating: 0,
      rg_content_score: 96.29,
      has_poster: true,
      poster_blur:
        "vGK_n8.8_3IU~qofxuoz00%MD*ofIVxaIAWBD%t8xtofbcIUofRjDibHayay",
      has_backdrop: true,
      backdrop_blur:
        "qFN^}A%M_Nj[00%L-;WC_2M{kDRjV@IUxut7D%?HIBbH%MWBozae-;xas:j[t7WBM{j[9ZWBIUWBxut7M{fQNGoyRioft7ofM{Rj",
      released_on: "2014-11-05T00:00:00",
      classification: "13+",
      sources: [
        "amazon_prime",
        "paramount_plus",
        "fubo_tv",
        "epix",
        "fx_tveverywhere",
        "directv",
        "mgm_plus",
      ],
      genres: [3, 5],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "4d949e14-b08b-47fb-bab0-22c732dbedf3",
      slug: "raiders-of-the-lost-ark-1981",
      content_type: "m",
      title: "Indiana Jones and the Raiders of the Lost Ark",
      overview:
        "In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before the Nazis can obtain its awesome powers.",
      availability_pros:
        "Available to watch free online (PlutoTV). Available to stream on a popular subscription service (Disney+ and Paramount+). Available to rent or buy from $2.89 on 6 services (iTunes, Apple TV, Google Play, and 3 others).",
      imdb_rating: 8.4,
      rt_critics_rating: 0,
      rg_content_score: 92.91,
      has_poster: true,
      poster_blur:
        "v8HAXyow01k80O-9JBNI0Ls,~BXm?EI;9bxZ[rs;r?R6Z$I@OsoH0gIpT0XS",
      has_backdrop: true,
      backdrop_blur:
        "qIJtxM00%gS%00~V%MM|WARjoJ%MIoRjxuM_0gWY-oM{bIbcRj%2-;M{M{-pM{M{x]Rks:j?M|a$t7j[ofoe%2ofR*WBM{s:t6WB",
      released_on: "1981-06-12T00:00:00",
      classification: "7+",
      sources: ["disney_plus", "paramount_plus", "plutotv"],
      genres: [5],
      on_services: true,
      on_free: true,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "67daab14-c08e-4be1-a957-8ba7c2525cef",
      slug: "top-gun-maverick-2020",
      content_type: "m",
      title: "Top Gun: Maverick",
      overview:
        "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video, Paramount+, Epix, and 2 others). Available to stream on a popular TV everywhere service (Epix). Available to rent or buy from $4.89 on 3 services (Apple TV, Prime Video, and Microsoft).",
      imdb_rating: 8.3,
      rt_critics_rating: 0,
      rg_content_score: 88.11,
      has_poster: true,
      poster_blur:
        "vRJQ.JE2?F4;~nE2XTjFxrS5oft59iXADjozM{t7%0NI9aoyxtxZx]NGjXxX",
      has_backdrop: true,
      backdrop_blur:
        "q67wQU~A0#0ME2s9%1={-oxtNHIpaes.W;S4NHR*afs:t6%1xZIpaejYWCR,t7%1ofM|oKayR*WCt6xas:NGRkR*WCs:$*xaWXNG",
      released_on: "2022-05-21T00:00:00",
      classification: "13+",
      sources: [
        "amazon_prime",
        "paramount_plus",
        "epix",
        "directv",
        "mgm_plus",
      ],
      genres: [3, 5],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "43051f20-d6b3-4768-bd01-814a4453f957",
      slug: "selfless-2015",
      content_type: "m",
      title: "Self/less",
      overview:
        "A dying real estate mogul transfers his consciousness into a healthy young body, but soon finds that neither the procedure nor the company that performed it are quite what they seem.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video). Available to rent or buy from $3.99 on 6 services (iTunes, Apple TV, Google Play, and 3 others).",
      imdb_rating: 6.5,
      rt_critics_rating: 0,
      rg_content_score: 78.18,
      has_poster: true,
      poster_blur:
        "vE9IG9lBNeR5xaD4V[xZn+ofxuX9McRit6SOH?R5xuxuysx^M_M{R4ROWExu",
      has_backdrop: true,
      backdrop_blur:
        "qVHCcc~U%LIBIps,-:xuMd%M%Lt7f5WBRjj?ESIVtRxtxtWBIoM|RkNIM|j[t6n~t7jsE2RlWER*RjoeoJt6oIa}RjWBjZt7oJay",
      released_on: "2015-07-10T00:00:00",
      classification: "13+",
      sources: ["amazon_prime"],
      genres: [5, 23],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "18780de0-7307-4e24-bd7d-4ae8c1d044f8",
      slug: "tar-2022",
      content_type: "m",
      title: "Tár",
      overview:
        "Set in the international world of Western classical music, the film centers on Lydia Tár, widely considered one of the greatest living composer-conductors and the very first female director of a major German orchestra.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video). Available to rent or buy from $5.99 on 2 services (Apple TV and Prime Video).",
      imdb_rating: 7.5,
      rt_critics_rating: null,
      rg_content_score: 79.16,
      has_poster: true,
      poster_blur:
        "v56RP@t7DiDiM|IUxuM|00In_4%N?bIVM{j@?bxvROIT9Fxu%1Io%1V@RjtS",
      has_backdrop: true,
      backdrop_blur:
        "q45#bBWB8_Rj_3t7D$R*DhoLXTj[M_aeo#axDit7?bt7D$WB%Mt7?wM{I9Rj%hW;RObHMwt8Ipoft6oJM|RjV@o1%Nj[Mxoft8oz",
      released_on: "2022-10-07T00:00:00",
      classification: "18+",
      sources: ["amazon_prime"],
      genres: [3, 37],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "059e9cc7-ed79-4dee-b4c3-670df437e61f",
      slug: "avatar-2009",
      content_type: "m",
      title: "Avatar",
      overview:
        "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      availability_pros:
        "Available to stream on a popular subscription service (Disney+, Philo, and DIRECTV STREAM). Available to stream on a popular TV everywhere service (AMC). Available to rent or buy from $3.99 on 5 services (iTunes, Apple TV, Prime Video, and 2 others).",
      imdb_rating: 7.9,
      rt_critics_rating: 0,
      rg_content_score: 91.84,
      has_poster: true,
      poster_blur:
        "v67-c{.A00E1E.tn%1xG0yNG=|%2:ziu9}I;MbVqW,Rh0eIT=_xCmiV?OaWY",
      has_backdrop: true,
      backdrop_blur:
        "q7AB35DN?HD*oz00x]oyMvtmxutmaeivM{V@Ekx]D*-;D%MwsVs:~qtRn$RORjXnMwkqH;-=x]xtV@%MRjV@NGx]NI%MV[D$%2Wo",
      released_on: "2009-12-16T00:00:00",
      classification: "13+",
      sources: ["disney_plus", "philo", "amc", "directv"],
      genres: [5, 13],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "e286d845-108d-4fb8-b634-8ec296d043d7",
      slug: "extraction-2020",
      content_type: "m",
      title: "Extraction",
      overview:
        "Tyler Rake, a fearless black market mercenary, embarks on the most deadly extraction of his career when he's enlisted to rescue the kidnapped son of an imprisoned international crime lord.",
      availability_pros:
        "Available to stream on a popular subscription service (Netflix and Netflix Basic).",
      imdb_rating: 6.7,
      rt_critics_rating: 0,
      rg_content_score: 80.67,
      has_poster: true,
      poster_blur:
        "vjG]8LS5IUt7~pR+M{j]xaR*NGWXofofofWWWBt7tRWVbHoKj]oeNGWCWCj@",
      has_backdrop: true,
      backdrop_blur:
        "qFI}6J*09vQ:020g^jbw*J$+R6Xlvh$xE*jFg4-BD*NL#;xuRjni-:X.%MIVIpR.sTt8t1k7s+RhslWBR,ixRRWCr^M|RQSPoLi_",
      released_on: "2020-04-24T00:00:00",
      classification: "18+",
      sources: ["netflix", "netflix_basic"],
      genres: [5, 10],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "b83434f7-991a-480b-a6ff-cba5b168d059",
      slug: "nope-2022",
      content_type: "m",
      title: "Nope",
      overview:
        "The residents of a lonely gulch in inland California bear witness to an uncanny and chilling discovery.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video). Available to rent or buy from $3.99 on 3 services (Apple TV, Prime Video, and Microsoft).",
      imdb_rating: 6.8,
      rt_critics_rating: 0,
      rg_content_score: 72.75,
      has_poster: true,
      poster_blur:
        "v23]G}pM4pbd0CWU_3j=]vZ|9DV=H;bfx^kYOeo%tokZ?aaGD#ac00V;-,aI",
      has_backdrop: true,
      backdrop_blur:
        "qF26%9kEWsayjbadaxaxXYfikDjYa#awjYf5jrabawf5kDj]flf5jCaIacfQkEkDfmflWAj[oJf6a~flj]j]o$kEWBadjYf5axay",
      released_on: "2022-07-21T00:00:00",
      classification: "18+",
      sources: ["amazon_prime"],
      genres: [19, 23],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "96aa5dc3-fd06-4697-8d01-06a8483328ae",
      slug: "amy-schumer-emergency-contact-2023",
      content_type: "m",
      title: "Amy Schumer: Emergency Contact",
      overview:
        "In her new comedy special, Emergency Contact, Amy Schumer once again talks about her life in an uncensored and hilarious way.",
      availability_pros:
        "Available to stream on a popular subscription service (Netflix and Netflix Basic).",
      imdb_rating: null,
      rt_critics_rating: null,
      rg_content_score: 66.09,
      has_poster: true,
      poster_blur:
        "vKCP6[xw0vR~irs+kBkX7UXT=O$,-@adI.s8H;s9tRJ%F^XA#raLR5M^Sdwf",
      has_backdrop: true,
      backdrop_blur:
        "qIA,S2534,}cK3S|$-NFQkx_T1R5s+Xls;aKB%$n#7ASxbxJJ5jFWUM^xwtRIpv~ScS|MdoztRnPjXNZjIogNrnQjXpIwOInoI$+",
      released_on: "2023-06-13T00:00:00",
      classification: null,
      sources: ["netflix", "netflix_basic"],
      genres: [9, 11],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "7aff33b0-11f4-473c-8370-6973fd32c79e",
      slug: "living-2022",
      content_type: "m",
      title: "Living",
      overview:
        "In 1950s London, a humorless bureaucrat decides to take time off work to experience life after receiving a grim diagnosis.",
      availability_pros:
        "Available to stream on a popular subscription service (Netflix). Available to rent or buy from $5.99 on 2 services (Apple TV and Prime Video). Coming soon to Netflix on July 4th, 2023 (PDT).",
      imdb_rating: 7.2,
      rt_critics_rating: null,
      rg_content_score: 75.25,
      has_poster: true,
      poster_blur:
        "v:Kw,:xaozxt~ps:ofayNGWBR*RjaxWBWBoLo}ofs:ofbvj[V@a}ofWCRjax",
      has_backdrop: true,
      backdrop_blur:
        "qiL#2w?H?a9FM{-;bHs:~qRkM{aeae%MRjRjM{RQRjt7t7WCWUWBfkofxaWBoLRjoft7ofjZayj@j@f6ofofoeoLNGt7WCofj[Rj",
      released_on: "2022-11-04T00:00:00",
      classification: "13+",
      sources: ["netflix"],
      genres: [3],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "8a9c2944-414d-4c3b-8c6f-86b97a804b4c",
      slug: "jurassic-world-dominion-2021",
      content_type: "m",
      title: "Jurassic World: Dominion",
      overview:
        "Four years after the destruction of Isla Nublar, Biosyn operatives attempt to track down Maisie Lockwood, while Dr Ellie Sattler investigates a genetically engineered swarm of giant insects.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video). Available to rent or buy from $3.99 on 4 services (Apple TV, Prime Video, Microsoft, and 1 other).",
      imdb_rating: 5.6,
      rt_critics_rating: null,
      rg_content_score: 76.06,
      has_poster: true,
      poster_blur:
        "v6IMrU0n06^g5D-7TD$i05},0-4@0%E*xG0$14nm,F?A0mwI}l^hEhJ7}-Iu",
      has_backdrop: true,
      backdrop_blur:
        "qNC=nXIr0Q-ltMM~xFba};Rl9xxYWWWCxFbH9foc$|RnRnt3t5WENIoeR+agxYkAf6R-$|a#E7s,-SR-NIWWRlj[oejZxER-NIoK",
      released_on: "2022-06-01T00:00:00",
      classification: "13+",
      sources: ["amazon_prime"],
      genres: [5, 26],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "582eaecb-6de4-461d-b093-b2b620b45921",
      slug: "three-thousand-years-of-longing-2022",
      content_type: "m",
      title: "Three Thousand Years of Longing",
      overview:
        "A lonely scholar, on a trip to Istanbul, discovers a Djinn who offers her three wishes in exchange for his freedom.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video, Paramount+, fuboTV, and 3 others). Available to stream on a popular TV everywhere service (Epix). Available to rent or buy from $5.99 on 2 services (Apple TV and Prime Video).",
      imdb_rating: 6.7,
      rt_critics_rating: null,
      rg_content_score: 75.48,
      has_poster: true,
      poster_blur:
        "v6Ga,vjJuht8UakX?abF0ys+mRV?~DIp00My4.xu5UW=8wae-pt5%~RjIASh",
      has_backdrop: true,
      backdrop_blur:
        "qpKJ+D~D.TSxWTRQMyxG8{nQIAW-bIoztRRjxHMxWBNGaeogofoes,odS1WUbbjIjbj[oLt6W.kCf8j[j[WBs:j]kCa}ofoLf5fj",
      released_on: "2022-08-24T00:00:00",
      classification: "18+",
      sources: [
        "amazon_prime",
        "paramount_plus",
        "fubo_tv",
        "epix",
        "directv",
        "mgm_plus",
      ],
      genres: [3, 4],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "ed303503-5d73-426b-9e7d-1ea19a679a3d",
      slug: "stan-lee-2023",
      content_type: "m",
      title: "Stan Lee",
      overview:
        "100 years of dreaming. 100 years of creating. 100 years of Stan Lee.",
      availability_pros:
        "Available to stream on a popular subscription service (Disney+).",
      imdb_rating: 7.7,
      rt_critics_rating: null,
      rg_content_score: 58,
      has_poster: true,
      poster_blur:
        "vBH_Y+J:5uIC5=rqESsl4TwGxCX8}gx@IDS~X9NyI@nO0qRR--wI18M}=?S4",
      has_backdrop: true,
      backdrop_blur:
        "q8K*rkvg00cEQ6i_GZi{}Yn4jGWBFyg3s+oL3rRj5kxa=HRPjcozvgj@RiRjlUsmMJS$10of-UX9RQnOoeoJVtkCrqt7T0NGWBs:",
      released_on: "2023-06-16T00:00:00",
      classification: null,
      sources: ["disney_plus"],
      genres: [7, 11],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "0bc031ed-52fb-4b22-9c2d-fb0c15861c4c",
      slug: "still-a-michael-j-fox-movie-2023",
      content_type: "m",
      title: "Still: A Michael J. Fox Movie",
      overview:
        "Follows the life of beloved actor and advocate Michael J. Fox, exploring his personal and professional triumphs and travails, and what happens when an incurable optimist confronts an incurable disease.",
      availability_pros:
        "Available to stream on a subscription service (Apple TV+).",
      imdb_rating: 8.2,
      rt_critics_rating: null,
      rg_content_score: 75.88,
      has_poster: true,
      poster_blur:
        "vFC~VRi~Mdae~AV@RjoLx@J8SdWot6X9oeNGrpr?WBn+IUoLxujZR*S2tRj[",
      has_backdrop: true,
      backdrop_blur:
        "q4A9$nN30KKKBB$iIC-4}QD%X9T0NFs,Ro={%Kxt?HxHIUEzSzR%EQNGr;v}IVx]%fI:-nxZRltR%MM|nNNd4:s.t6NGRQnOxCX9",
      released_on: "2023-05-12T00:00:00",
      classification: "18+",
      sources: ["apple_tv_plus"],
      genres: [7, 11],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "a737a580-4abf-416e-a638-cfbb15d9d24e",
      slug: "transformers-age-of-extinction-2014",
      content_type: "m",
      title: "Transformers: Age of Extinction",
      overview:
        "When humanity allies with a bounty hunter in pursuit of Optimus Prime, the Autobots turn to a mechanic and his family for help.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video, Paramount+, Epix, and 2 others). Available to stream on a popular TV everywhere service (Epix). Available to rent or buy from $2.99 on 5 services (iTunes, Apple TV, Prime Video, and 2 others).",
      imdb_rating: 5.6,
      rt_critics_rating: 0,
      rg_content_score: 76.92,
      has_poster: true,
      poster_blur:
        "vMEera~B~Axu_2xaS5t758E257oJ-5Rii^WBxsaeR*NHN{WYS5oL%1ozxtW.",
      has_backdrop: true,
      backdrop_blur:
        "qHCr$F$LD*$fSjI@WXoIKPNGNHNd%1r=oeM|9|I;X8NHxuR*R*ad}?aKxD$LX9R,RkWqJCn%jGNHxtnit6WXS5R*S4I;bvIpWCs.",
      released_on: "2014-06-25T00:00:00",
      classification: "13+",
      sources: [
        "amazon_prime",
        "paramount_plus",
        "epix",
        "directv",
        "mgm_plus",
      ],
      genres: [5, 26],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "2f13471c-47b4-4ed5-adf6-ff65fa4dbd39",
      slug: "tetris-2023",
      content_type: "m",
      title: "Tetris",
      overview:
        "The story of how one of the world's most popular video games found its way to players around the globe. Businessman Henk Rogers and Tetris inventor Alexey Pajitnov join forces in the USSR, risking it all to bring Tetris to the masses.",
      availability_pros:
        "Available to stream on a subscription service (Apple TV+).",
      imdb_rating: 7.4,
      rt_critics_rating: null,
      rg_content_score: 78.1,
      has_poster: true,
      poster_blur:
        "vkLX6*od.8oM~paytRoMI;ayIAj[x]ofs:RktQj[ofWBe.a}M|j@WBkBozWV",
      has_backdrop: true,
      backdrop_blur:
        "qbNdBkf6_MofIUV@ozof~Wj?D*f6aeWBtRofE2j[smWVx[bIM{bHtRj[WBa{WqofoLWBozoeRjWVkCj[oLaxWBo0oLoLoLWqRkWB",
      released_on: "2023-03-24T00:00:00",
      classification: "18+",
      sources: ["apple_tv_plus"],
      genres: [3, 7],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "c4cd9cf5-32be-4638-9805-82c7fa8c1b3b",
      slug: "true-lies-1994",
      content_type: "m",
      title: "True Lies",
      overview:
        "A fearless, globe-trotting, terrorist-battling secret agent has his life turned upside down when he discovers his wife might be having an affair with a used-car salesman while terrorists smuggle nuclear war heads into the United States.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video, Paramount+, fuboTV, and 3 others). Available to stream on a popular TV everywhere service (Epix and NBC).",
      imdb_rating: 7.3,
      rt_critics_rating: 0,
      rg_content_score: 83.45,
      has_poster: true,
      poster_blur:
        "vGKwe1BpPV}S00My9Z-p9vWU-TX9?]-piw569GnOxuN{IVRj%Moz.8-pM{Io",
      has_backdrop: true,
      backdrop_blur:
        "qzMjp:wH.TofkCM|Mxxu?bX9%1o#jFV?WVt7bbRjM{xaNGR*f+R*XSadWBozWAkCt7ayjtW=s:snWXR*t7s.oejZWWj[oJWVWVWB",
      released_on: "1994-07-15T00:00:00",
      classification: "18+",
      sources: [
        "amazon_prime",
        "paramount_plus",
        "fubo_tv",
        "epix",
        "nbc_tveverywhere",
        "directv",
        "mgm_plus",
      ],
      genres: [5, 9],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "a66a1ec7-63b9-465e-8062-ec2f253dac90",
      slug: "game-night-2018",
      content_type: "m",
      title: "Game Night",
      overview:
        "A group of friends who meet regularly for game nights find themselves entangled in a real-life mystery when the shady brother of one of them is seemingly kidnapped by dangerous gangsters.",
      availability_pros:
        "Available to watch free online (TruTV). Available to stream on a subscription service (TVision). Available to stream on a popular TV everywhere service (TBS, TNT, and TruTV). Available to rent or buy from $3.99 on 4 services (iTunes, Apple TV, Microsoft, and 1 other).",
      imdb_rating: 6.9,
      rt_critics_rating: 0,
      rg_content_score: 82.63,
      has_poster: true,
      poster_blur:
        "v9EC%yEM00t6k=%10Ki_Pq9Z%Mt700t7W?tl^P$%-ps;8wIo-pob01WY%L-o",
      has_backdrop: true,
      backdrop_blur:
        "qID9FlIoxZNFR*s.s:xa0gxtxYV@Rjs:ogof?ZRkRlRjRkofWCR+0MbIjZxaofNGt7oK~TM|ofoft6WBWAjZ4:s.t6WEj]t6M|R*",
      released_on: "2018-02-15T00:00:00",
      classification: "18+",
      sources: [
        "amazon_prime",
        "tbs",
        "tnt",
        "trutv_tveverywhere",
        "tvision",
        "trutv",
      ],
      genres: [9, 23],
      on_services: true,
      on_free: true,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "08410880-3921-4f15-9714-9f0947705d24",
      slug: "blood-gold-2023",
      content_type: "m",
      title: "Blood & Gold",
      overview:
        "At the end of World War II, a German soldier is looking for his daughter while an SS troop is looking for a Jewish treasure.",
      availability_pros:
        "Available to stream on a popular subscription service (Netflix and Netflix Basic).",
      imdb_rating: null,
      rt_critics_rating: null,
      rg_content_score: 66.09,
      has_poster: true,
      poster_blur:
        "vILgtt00?wRO020KROoLyYo~aJt6jXM{t8%LtSxtn#s;oeW?RkjYtSIURQt7",
      has_backdrop: true,
      backdrop_blur:
        "q8AS-,0}4:R64;-.~UNb~UR+NGIVIV%2-:R*02-UtQtQ={IpIpf602xZxa-:-:IV57n%9ZkB%1t7Shr=E2s:%0R*oyRkRkWBjsxt",
      released_on: "2023-05-26T00:00:00",
      classification: null,
      sources: ["netflix", "netflix_basic"],
      genres: [3, 5],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "f10dfc85-3cd0-4480-a3c6-8ab67e3b70fe",
      slug: "terminator-2-judgment-day-1991",
      content_type: "m",
      title: "Terminator 2: Judgment Day",
      overview:
        "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten year old son John from an even more advanced and powerful cyborg.",
      availability_pros:
        "Available to stream on a popular subscription service (Netflix, Netflix Basic, and DIRECTV STREAM). Available to stream on a popular TV everywhere service (AMC). Available to rent or buy from $1.99 on 7 services (iTunes, Apple TV, Google Play, and 4 others).",
      imdb_rating: 8.6,
      rt_critics_rating: 0,
      rg_content_score: 94.04,
      has_poster: true,
      poster_blur:
        "v58qZ~n#4:XA0KRiib-=}lRj4mx]0eo~?wRi-U%gRiMxIUMwxYMx4oRP-;Rk",
      has_backdrop: true,
      backdrop_blur:
        "qDBD,9sRpMXVR2rotSSjRka}ROj?t8ayRjbIohj]WAV?oeo#W=WBWAfQj]azayj[j[WBWUazjsoLj[WVWVoJaxjsj]a}WVayoJoK",
      released_on: "1991-07-03T00:00:00",
      classification: "18+",
      sources: ["netflix", "netflix_basic", "amc", "directv"],
      genres: [26, 5],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "41202aae-3aa0-4e68-9670-a2da6e2482ae",
      slug: "the-wolf-of-wall-street-2013",
      content_type: "m",
      title: "The Wolf of Wall Street",
      overview:
        "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video, Paramount+, fuboTV, and 3 others). Available to stream on a popular TV everywhere service (Epix). Available to rent or buy from $2.99 on 5 services (iTunes, Apple TV, Prime Video, and 2 others).",
      imdb_rating: 8.2,
      rt_critics_rating: 0,
      rg_content_score: 93.35,
      has_poster: true,
      poster_blur:
        "vQE2LDxBI@ae};bIENofMwS5I=j[NFWBt7WBIrofxDfkXAt6adkCJCR%t6j[",
      has_backdrop: true,
      backdrop_blur:
        "qJH_rs54?cMdB;}@K6xa0#MKNGNewJJ8wIR*g1xa?HtSslM{NGxGjFIURjnNWUozoMWq-;kCt6WobHogS3e.R*M{WBV@fkoeoLbb",
      released_on: "2013-12-25T00:00:00",
      classification: "18+",
      sources: [
        "amazon_prime",
        "paramount_plus",
        "fubo_tv",
        "epix",
        "directv",
        "mgm_plus",
      ],
      genres: [3, 10],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "698912fe-d93a-473c-a7f0-217924402b0f",
      slug: "ghosted-2023",
      content_type: "m",
      title: "Ghosted",
      overview:
        "Cole falls head over heels for enigmatic Sadie, but then makes the shocking discovery that she's a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the world.",
      availability_pros:
        "Available to stream on a subscription service (Apple TV+).",
      imdb_rating: 5.8,
      rt_critics_rating: null,
      rg_content_score: 72.11,
      has_poster: true,
      poster_blur:
        "vSIM.q~Bj?R*^*S~OYnh%1ozxanO?bo}niV[TKJAR*NGr=$g%1RjT0f+s.WB",
      has_backdrop: true,
      backdrop_blur:
        "qAKJSo-7]~E1-p%1t5s:CT%2D%V@?GxZV@s:?^oL01$f-pt7IUxt%g%1R4Rjx]oyM{W;JC%MMdW;tlM{xsE2-;OYE1xZozE2t6Rj",
      released_on: "2023-04-21T00:00:00",
      classification: "13+",
      sources: ["apple_tv_plus"],
      genres: [4, 5],
      on_services: true,
      on_free: false,
      on_rent_purchase: false,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "6037570a-6b25-4843-be68-1bac14f4604d",
      slug: "spider-man-homecoming-2017",
      content_type: "m",
      title: "Spider-Man: Homecoming",
      overview:
        "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
      availability_pros:
        "Available to stream on a popular subscription service (Disney+ and DIRECTV STREAM). Available to stream on a popular TV everywhere service (Starz). Available to rent or buy from $2.99 on 5 services (iTunes, Apple TV, Prime Video, and 2 others).",
      imdb_rating: 7.4,
      rt_critics_rating: 0,
      rg_content_score: 88.36,
      has_poster: true,
      poster_blur:
        "vRF~UA^+%gX8u6NyWVof5RXTMxxF?a-;n$s.o#Ipg3tRxZnOtRtlxVaJR*R*",
      has_backdrop: true,
      backdrop_blur:
        "qzLEHFt7tRV@Rjt7ozRj~qkCfkWBRjkCj[WBt7WBRjj[ofayWCofIoWBaeofozWBaeoft7t7ayj[fkj@fQj[WVWBj[ayWBayjuj[",
      released_on: "2017-07-05T00:00:00",
      classification: "13+",
      sources: ["disney_plus", "starz", "directv"],
      genres: [3, 5],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "6cc8fe94-b6ef-4045-81be-335bffc38abd",
      slug: "heat-1995",
      content_type: "m",
      title: "Heat",
      overview:
        "A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.",
      availability_pros:
        "Available to watch free online (Plex). Available to stream on a popular subscription service (Netflix and Netflix Basic). Available to rent or buy from $3.99 on 5 services (iTunes, Apple TV, Prime Video, and 2 others).",
      imdb_rating: 8.3,
      rt_critics_rating: 0,
      rg_content_score: 90.66,
      has_poster: true,
      poster_blur:
        "vB6ux8McDhtRDho#xut8Q+tmo#RiyEVrRnRO8wtR%MWEx^fmR4kX.AR4Rjt7",
      has_backdrop: true,
      backdrop_blur:
        "qbNTwN4n_3_N%NRjt7%M_3xtE1RjR%jGRPR*kCt8RjV@ofa_t7t7IpxuofjEV@ogofayR*kCWAadjZoej[V@xajsM{R*kCflfkof",
      released_on: "1995-12-15T00:00:00",
      classification: "18+",
      sources: ["netflix", "netflix_basic", "plex_free"],
      genres: [3, 10],
      on_services: true,
      on_free: true,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
    {
      id: "10b751ad-7e2f-428c-8d16-85d1dcc5ef25",
      slug: "arrival-2016",
      content_type: "m",
      title: "Arrival",
      overview:
        "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
      availability_pros:
        "Available to stream on a popular subscription service (Prime Video, Paramount+, fuboTV, and 3 others). Available to stream on a popular TV everywhere service (Epix). Available to rent or buy from $2.99 on 6 services (iTunes, Apple TV, Google Play, and 3 others).",
      imdb_rating: 7.9,
      rt_critics_rating: 0,
      rg_content_score: 90.39,
      has_poster: true,
      poster_blur:
        "vHEfTo01~qWXXqM{ogR*00=_9FWA_2WBs+s.V?Rkt7ofE1j?RkWBs.t7t7az",
      has_backdrop: true,
      backdrop_blur:
        "qfD,ZUXQM{a0ozWAo0fS?wWFRjadozV@jtofyEafaeWVj]aekCf*%gjZaefljZaya}a#tRofofWVn%bHWBoeW=jaofofaea#ayj?",
      released_on: "2016-11-10T00:00:00",
      classification: "13+",
      sources: [
        "amazon_prime",
        "paramount_plus",
        "fubo_tv",
        "epix",
        "directv",
        "mgm_plus",
      ],
      genres: [3, 23],
      on_services: true,
      on_free: false,
      on_rent_purchase: true,
      user_rating: null,
      tracking: false,
      watchlisted: false,
      seen: false,
      season_count: 0,
      featured_services: [],
      episode_source_count: 0,
    },
  ],
};

export default movies;
